### ISSUE TITLE
Is the idea here that you're going to add all of the samples currently shipping with ICN?

### ISSUE THREAD

**Issue by astrodad** [ibm-ecm/ibm-content-navigator-samples#1]
There are several sample plugins that are shipped with ICN. Are they all going to end up here?

**Comment by shenoya** [comment]
We are currently in the process of publishing our new sample plug-ins here. But all samples previously shipped with ICN will also eventually move to this repository on GitHub.

**Comment by astrodad** [comment]
Ok thanks! Good to know that new samples are coming. Are you accepting pull requests for new plugins that customers might want to share?

**Comment by Arronla** [comment]
Sure, if you have sample plugins you want to show, send us a pull request, and we can review and decide whether to push as well.
