### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by bhavik15vora** [ibm-ecm/ibm-content-navigator-samples#4]
![image](https://user-images.githubusercontent.com/11164148/42012664-15eded4e-7aa2-11e8-8b50-8c676269d2e2.png)

There is error as displayed in above image. I want to know which version of navigatorAPI is used for this plugin?

**Comment by bhavik15vora** [comment]
Is there any customlayout

**Comment by wangweiu** [comment]
Please use ICN 3.0.4
