### ISSUE TITLE
Build fails with PDE cycle error

### ISSUE THREAD

**Issue by sindhoor7** [ibm-ecm/ibm-content-navigator-samples#46]
At step#6 of build process it fails with below error for Eclipse Plug-in: 

A cycle was detected when generating the classpath com.ibm.ecm.icn.plugin_2.0.3, org.eclipse.wst.jsdt.core_2.0.302.v201903222047, com.google.javascript_0.0.20160315.v20161124-1903, org.apache.ant_1.10.5.v20190526-1402, javax.activation_1.1.0.v201211130549, javax.mail_1.4.0.v201005080615, javax.activation_1.1.0.v201211130549.

![image](https://user-images.githubusercontent.com/13710119/111612379-6a062880-8803-11eb-85b2-dd8db243a4d3.png)

**Comment by PurpleZhang** [comment]
Hi, please check the last part of the README:
For Eclipse Oxygen

The buildTools.xml will cause a cycle error. You can just export the project as eclipse plugin. Check on "Allow for binary cycles in target platform", and check OFF "Use class files compiled in the workspace". The execution environments may need to be changed to java 1.8. Then copy the plugin jar file to eclipse dropins folder.

**Comment by PurpleZhang** [comment]
Please let me know if the last comment can not solve the issue.
