### ISSUE TITLE
EmailLookupPlugin Send button remains disabled after selecting a user

### ISSUE THREAD

**Issue by yetanothersteve** [ibm-ecm/ibm-content-navigator-samples#6]
The send button remains disabled after selecting 1 or more users from the drop down. 

This is with ICN 3.0.11. 

If I remove the emailLookupPlugin.jar from the desktop and then try it again, the Send button is activated when a new email is added to the To line.

**Comment by emshedu** [comment]
Hi, thank you for bringing up the issue! 
I have replicated it. I am now investigating to see what the issue could be

**Comment by emshedu** [comment]
Hi! Hope all is well. A fix will be available soon. We thank you for utilising this plugin

**Comment by yetanothersteve** [comment]
Thank you for researching. I look forward to testing the update.

**Comment by emshedu** [comment]
HI The updated version of the plugin is now available. We made some updates to the plugin functionality to assist copy and paste functionality. Please let me know if you find everything working well

**Comment by emshedu** [comment]
Good day [yetanothersteve](https://github.com/yetanothersteve)
Are you experiencing the issue following using the updated code

**Comment by yetanothersteve** [comment]
The updated code fixed the problem. Thanks.
