### ISSUE TITLE
Is eclipse plugin ready for ICN 3.0.3?

### ISSUE THREAD

**Issue by omoralesm** [ibm-ecm/ibm-content-navigator-samples#9]
Hi,

First of all, thanks a lot for creating these samples, they are very useful; as you can see in the title, I would like to know if the eclipse plugin is ready for ICN 3.0.3? Thanks in advanced.

**Comment by PurpleZhang** [comment]
Hi,

Sure it is. Actually, ICN has no big change for plugin part. The build is to against different version of eclipse.

**Comment by omoralesm** [comment]
Thanks a lot for the confirmation.
