### ISSUE TITLE
Docusign email signature is sending the document twice within the email

### ISSUE THREAD

**Issue by xavnicnsi** [ibm-ecm/ibm-content-navigator-samples#9]
Hello emshedu,

I was doing some testing and found that the email for signature is sending the document twice to review. In my test, I have 2 recipients and as the document is sent twice within the email, my both signees have to complete twice the signing part before the process is completed
below the both review to do by each recipient
![image](https://user-images.githubusercontent.com/99875865/157818957-601ffec8-243a-45b9-93c8-8e9efc7c45ce.png)

**Comment by emshedu** [comment]
Hi! i believe the double send is a result of Docusign API. ICN sends one, and docusign sends a follow up. However one can complete the sign-in process with any one of the notification. Clicking on "review document" redirects you to docusign app, where the signature process is actually done. i do not see that any user has to append signature on both, in your case four emails before the signing process is complete.
Did i understand the problem statement above?

**Comment by xavnicnsi** [comment]
From the last test I ran, I was unable to get the signing process complete until each recipient review both documents within the same email. In my docusign template, I filled the email of each recipient, and then from ICN , I filled the email of each recipient (same as the template) as asked by the plugin. 
I'll ran a test lter today and let you know the result.
thanks anyway!

**Comment by xavnicnsi** [comment]
Hello,
if name field is empty in the template and only the email address is filled for each recipient in the template, then only 1 document is sent for signing process for each recipient to complete the whole signing process. So that part is clarified.
Tx. I'll be waiting for the upcoming update about the plugin

**Comment by emshedu** [comment]
Thank you. I will make sure to update you once it is ready

**Comment by xavnicnsi** [comment]
Hello emshedu, May I ask you if you have any visibility for auto checkin, when it would be available?
TIA

**Comment by emshedu** [comment]
The autocheckin feature should be ready and merged next week

**Comment by xavnicnsi** [comment]
Great news! Thanks emshedu!

**Comment by emshedu** [comment]
Hi the plugin has been updated with the latest code. Please let me know if you find everything well

**Comment by xavnicnsi** [comment]
Hi, many thanks. I'll test it out and let you know. Tx again
